#!/bin/bash
clear
user_name=hanna
password=1973
read -p "Enter Your name " user  
read -p "Enter your password " pass
if [ $user == $user_name ] &&  [ $pass == $password ]
 then 
	echo "Right username and password"
else 
	if  [ $user == $user_name ]
		then 
		echo "Wrong password" 
	elif [ $pass == $password ]
		then echo "Wrong username" 
	else
		echo "Wrong username and password" 
	fi
fi
