#!/bin/sh

set -u
set -e

# Add a console on tty1
if [ -e ${TARGET_DIR}/etc/inittab ]; then
    grep -qE '^tty1::' ${TARGET_DIR}/etc/inittab || \
	sed -i '/GENERIC_SERIAL/a\
tty1::respawn:/sbin/getty -L  tty1 0 vt100 # HDMI console' ${TARGET_DIR}/etc/inittab
fi

## PermitRootLogin for ssh
sed -i '/#PermitRootLogin prohibit-password/c\PermitRootLogin yes' output/target/etc/ssh/sshd_config 


## change prompt to raspi> with red color
sed -i "/export PS1=/c\                 export PS1='\\\e[0;31mraspi> \\\e[m '"  output/target/etc/profile


## aliasing ls -lah
echo 'alias las="ls -lah"' >> output/target/etc/profile


## make static ip
cat > output/target/etc/network/interfaces << EOL
# interface file auto-generated by buildroot

auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
        pre-up /etc/network/nfs_check
        address 192.168.1.200
        netmask 255.255.255.0
        wait-delay 15
        hostname $(hostname)
EOL