#!/bin/bash
set -e
sudo modprobe snd-bcm2835 #This will wire up the sound card with alsa
PLAYER="/root/superMusic/"
test -d ${PLAYER} || exit 1
i=0
curser=0
button_state=0
FirstTimeFlag=0
FirstTimeFlag17=0
PlayingFlag=0
while IFS= read -r var
do 
  i=$[ $i +1 ]
  arr+=($var)
done <<< $(find $PLAYER -iname "*mp3") 
Max=$[$i -1]
Min=0
if [ ! -d /sys/class/gpio/gpio4 ] ; then # check if export process has done before
    echo "4" > /sys/class/gpio/export
    echo "in" > /sys/class/gpio/gpio4/direction
fi
if [ ! -d /sys/class/gpio/gpio17 ] ; then # check if export process has done before
    echo "17" > /sys/class/gpio/export
    echo "in" > /sys/class/gpio/gpio17/direction
fi
if [ ! -d /sys/class/gpio/gpio18 ] ; then # check if export process has done before
    echo "18" > /sys/class/gpio/export
    echo "in" > /sys/class/gpio/gpio18/direction
fi

while true; do
  
  if [ $(cat /sys/class/gpio/gpio4/value) -eq 1 ] ; then #if anyone pushed the button ==> toggle 
    #toggle button state
    if [ $FirstTimeFlag -eq 0 ] ; then 
      mpg123 ${arr[@]:$curser} &
      FirstTimeFlag=1
      button_state=1
      PlayingFlag=1
      sleep 0.5
      continue
    fi
    if [ $button_state -eq 0 ]
      then
      killall -CONT mpg123
      PlayingFlag=1
      button_state=1
      sleep 0.3
    elif [ $button_state -eq 1 ]
    then
      killall -STOP  mpg123
      PlayingFlag=0
      button_state=0
      sleep 0.3 # to allow finger release
    fi
  fi

  if [ $(cat /sys/class/gpio/gpio17/value) -eq 1 ] ; then #next
     if [ $PlayingFlag -eq 1 ] ; then 

      if [ $curser -lt $Max ] ; then 
        sudo killall -KILL mpg123
        sleep 0.5
        curser=$[ $curser +1 ]
        echo "$curser"
        echo 
        mpg123 ${arr[@]:$curser} &
        
      fi
    fi
  fi
  if [ $(cat /sys/class/gpio/gpio18/value) -eq 1 ] ; then #prev
     if [ $PlayingFlag -eq 1 ] ; then 
      if [ $curser -gt $Min ] ; then
        sudo killall -KILL mpg123 
        sleep 0.5
        curser=$[ $curser -1 ]
        echo "$curser"
        mpg123 ${arr[@]:$curser} &
        
      fi
    fi
  fi 
done
